# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpectraPlugin
                                 A QGIS plugin
 Smart Platform for Earth's Collected Imagery Analysis - AI-powered remote sensing analysis tool (object detection, classification, segmentation, change detection)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-22
        copyright            : (C) 2025 by Deepresense
        email                : deepresense@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpectraPlugin class from file SpectraPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .spectra_plugin import SpectraPlugin
    return SpectraPlugin(iface)
